# Runs the tests.

name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install Tools
        run: python -m pip install --upgrade pip pytest pytest-cov

      - name: Install Requirements
        run: pip install -r requirements1.txt

      - name: Test
        run: pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Publish Test Results
        # To make this work, you have to enable "read/write" permissions
        # in the "repo settings"
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ always() }}
        with:
           # Comments don't work with fork PRs anyway
           comment_mode: off
           files: |
             junit/test-results.xml